-- Disable RLS on tables that don't have policies yet, 
-- preventing "permission denied" errors when using SUPABASE_ANON_KEY.

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE professionals DISABLE ROW LEVEL SECURITY;
ALTER TABLE services DISABLE ROW LEVEL SECURITY;
ALTER TABLE medical_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE insurances DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_integrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE system_integrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE password_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
