// ============================================
// clinxia — Dados fictícios da plataforma
// Usado pelo SuperAdminDashboard para demonstrar
// a inspeção e impersonação de clínicas
// ============================================

export const DEMO_PLATFORM_CLINICS = [
  {
    id: 'clinic-1',
    name: 'Lumina Odontologia',
    plan: 'ultra' as const,
    status: 'active' as const,
    users: 5,
    patients: 156,
    mrr: 697,
    owner: 'Dr. Lucas Silva',
    email: 'lucas@lumina.com.br',
    phone: '(11) 3456-7890',
    cnpj: '45.678.901/0001-23',
    address: {
      street: 'Av. Paulista, 1000',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01310-100',
    },
    specialties: ['Ortodontia', 'Implante', 'Endodontia', 'Periodontia'],
    created_at: '2024-06-15T00:00:00.000Z',
  },
  {
    id: 'clinic-2',
    name: 'Estética Premium SP',
    plan: 'pro' as const,
    status: 'active' as const,
    users: 3,
    patients: 89,
    mrr: 397,
    owner: 'Dra. Camila Neves',
    email: 'camila@esteticapremium.com.br',
    phone: '(11) 2222-3333',
    cnpj: '98.765.432/0001-11',
    address: {
      street: 'Rua Oscar Freire, 500',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01426-000',
    },
    specialties: ['Tratamentos Faciais', 'Harmonização Facial', 'Laser', 'Depilação'],
    created_at: '2025-03-20T00:00:00.000Z',
  },
  {
    id: 'clinic-3',
    name: 'OdontoVida Clínica',
    plan: 'basic' as const,
    status: 'trial' as const,
    users: 2,
    patients: 23,
    mrr: 0,
    owner: 'Dr. Rafael Costa',
    email: 'rafael@odontovida.com.br',
    phone: '(21) 3333-4444',
    cnpj: '12.345.678/0001-55',
    address: {
      street: 'Av. Atlântica, 2000',
      city: 'Rio de Janeiro',
      state: 'RJ',
      zipCode: '22010-000',
    },
    specialties: ['Odontopediatria', 'Dentística'],
    created_at: '2025-05-10T00:00:00.000Z',
  },
  {
    id: 'clinic-4',
    name: 'Sorriso Perfeito',
    plan: 'pro' as const,
    status: 'active' as const,
    users: 5,
    patients: 210,
    mrr: 397,
    owner: 'Dra. Amanda Reis',
    email: 'amanda@sorrisoperfeito.com.br',
    phone: '(19) 4444-5555',
    cnpj: '34.567.890/0001-22',
    address: {
      street: 'Av. Campos Salles, 800',
      city: 'Campinas',
      state: 'SP',
      zipCode: '13010-000',
    },
    specialties: ['Ortodontia', 'Implante', 'Prótese Dentária', 'Cirurgia Oral'],
    created_at: '2025-02-01T00:00:00.000Z',
  },
];

